source 'https://rubygems.org'
gem 'metadata-json-lint'
gem 'puppetlabs_spec_helper', '>= 1.0.0'
gem 'puppet-blacksmith', '>= 1.0.0'
gem 'puppet-lint', '>= 1.0.0'
gem 'facter', '>= 1.7.0'
gem 'rainbow', '>= 2.1.0', '< 2.2.0'
gem 'rspec-puppet'
gem 'rubocop'
gem 'rspec'
gem 'rake'
gem 'travis'
gem 'git'
gem 'docker'
gem 'docker-api'
gem 'puppet', '= 3.7.4'
gem 'beaker', ' = 2.52.0'
gem 'beaker-rspec', ' = 5.6.0'
gem 'beaker-hostgenerator'
gem 'nokogiri', '= 1.7.0.1'
gem 'unf_ext'
gem 'serverspec'
